language: cpp
os: linux
dist: bionic
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo dpkg --add-architecture i386
  - sudo apt -y update
  - sudo apt -y install qemu-user-static:i386
services:
  - docker
compiler:
  - gcc
jobs:
  include:
  - name: "Pi stretch"
    env: DOCKERFILE=Dockerfile-pi-stretch DISTRO=stretch
  - name: "Pi buster"
    env: DOCKERFILE=Dockerfile-pi-buster DISTRO=buster
script: |

        docker build -f ${DOCKERFILE} --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} -t=openhd/${DISTRO} .
        docker create -it -v ${TRAVIS_BUILD_DIR}:/src --name openhd_${DISTRO}_build openhd/${DISTRO}
        docker start -i openhd_${DISTRO}_build
