language: cpp
os: linux
dist: bionic
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo dpkg --add-architecture i386
  - sudo apt -y update
  - sudo apt -y install qemu-user-static:i386
services:
  - docker
compiler:
  - gcc
cache:
  - $HOME/.openhd_cache
jobs:
  include:
  - name: "Pi stretch"
    env: PLATFORM=pi DISTRO=stretch
  - name: "Pi buster"
    env: PLATFORM=pi DISTRO=buster
script: ./build_docker.sh $PLATFORM $DISTRO
